### PR TITLE
Adding landscape support

### PR DESCRIPTION
**Pull request by rknell**
Allowing the user to pass the landscape flag through the options object. Maintains the landscape flag key from puppeteer (ie landscape and not isLandscape)

### CODE REVIEW

**Review by FelixFurtmayr — APPROVED** [review]

**Comment by FelixFurtmayr** [comment]
Hi rknell, thank you for the contribution :-)

Just one question before I merge it - you did not add default option, which means it will pass a "undefined", if there is nothing specified. Does it still work.

**Comment by rknell** [comment]
since it was undefined before I figure it should gracefully handle it, but
give me a moment, i've got it open now to test
<http://www.snappy-apps.com.au>

**Comment by rknell** [comment]
Yep. 100% can confirm it works as it used to without any option set, and goes to landscape when you set landscape to true

**Comment by FelixFurtmayr** [comment]
thanks for the confirmation

**Pull request merged**
